/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TransactionsLazyImport = createFileRoute('/transactions')()
const PreferencesLazyImport = createFileRoute('/preferences')()
const AccountsLazyImport = createFileRoute('/accounts')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TransactionsLazyRoute = TransactionsLazyImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/transactions.lazy').then((d) => d.Route))

const PreferencesLazyRoute = PreferencesLazyImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/preferences.lazy').then((d) => d.Route))

const AccountsLazyRoute = AccountsLazyImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/accounts.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsLazyImport
      parentRoute: typeof rootRoute
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesLazyImport
      parentRoute: typeof rootRoute
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/accounts': typeof AccountsLazyRoute
  '/preferences': typeof PreferencesLazyRoute
  '/transactions': typeof TransactionsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/accounts': typeof AccountsLazyRoute
  '/preferences': typeof PreferencesLazyRoute
  '/transactions': typeof TransactionsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/accounts': typeof AccountsLazyRoute
  '/preferences': typeof PreferencesLazyRoute
  '/transactions': typeof TransactionsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accounts' | '/preferences' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accounts' | '/preferences' | '/transactions'
  id: '__root__' | '/' | '/accounts' | '/preferences' | '/transactions'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AccountsLazyRoute: typeof AccountsLazyRoute
  PreferencesLazyRoute: typeof PreferencesLazyRoute
  TransactionsLazyRoute: typeof TransactionsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AccountsLazyRoute: AccountsLazyRoute,
  PreferencesLazyRoute: PreferencesLazyRoute,
  TransactionsLazyRoute: TransactionsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/accounts",
        "/preferences",
        "/transactions"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/accounts": {
      "filePath": "accounts.lazy.tsx"
    },
    "/preferences": {
      "filePath": "preferences.lazy.tsx"
    },
    "/transactions": {
      "filePath": "transactions.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
